### ISSUE TITLE
Errores al crear los inmuebles

### ISSUE THREAD

**Issue by valleedev** [EmmanuelOcLe/inmobiliaria#1]
# Comportamiento Esperado
Se espera que en el formulario de creación debe aparecer un campo de tipo selección del tipo de oferta(alquiler, venta, venta y alquiler).
# Comportamiento Actual
El formulario no cuenta con este campo
![image](https://github.com/user-attachments/assets/e790f5a6-6782-4409-b775-51d47ec71982)
# Pasos a Reproducir
1. Añadir el input de tipo select en el formulario
2. Verificar que si se este enviando esa información a la base de datos

**Comment by michael-myers-myke** [comment]
# Solucion
Solucione el error del issue ya que los datos no se almacenaban en la base de datos por un error en la insercion a la base de datos
<img width="884" alt="form_Crear php" src="https://github.com/user-attachments/assets/3fac4ad9-02e0-4ee0-b65c-a45fa27d3b82" />
