### ISSUE TITLE
No se muestra la foto de los inmuebles deshabilitados

### ISSUE THREAD

**Issue by EmmanuelOcLe** [EmmanuelOcLe/inmobiliaria#10]
# Evidencia
![imagen](https://github.com/user-attachments/assets/7590edad-ca1d-4243-9655-a1bed5aeddbd)

**Comment by valleedev** [comment]
Se añade enrutamiento dinámico para mostrar las imagenes
![image](https://github.com/user-attachments/assets/eb083ea2-3526-41dd-9135-8d2e7cd18dc1)
