### ISSUE TITLE
Las cards de las propiedades en el index se duplican 

### ISSUE THREAD

**Issue by EmmanuelOcLe** [EmmanuelOcLe/inmobiliaria#11]
# Las cards de las propiedades en el index se duplican luego de usar los filtros

En el video a continuación se muestra cómo al principio se encuentra bien la cantidad de propiedades y  se comprueba mostrando la base de datos.
Cuando se aplican filtros, se duplica la cantidad de cards que deberían haber y tambien se muestra que en la base de datos no aparecen tantos registros

https://github.com/user-attachments/assets/fec46265-55f1-4425-b249-45bb0172b3f4

**Comment by valleedev** [comment]
Se elimina el filtro porque no era un requerimiento, se deja guardado en texto plano para **posible** implementación
