### ISSUE TITLE
Se pueden crear propiedades con datos vacíos 

### ISSUE THREAD

**Issue by EmmanuelOcLe** [EmmanuelOcLe/inmobiliaria#12]
# Resultado actual
Se pueden crear propiedades con campos vacíos. El único campo que es por ahora obligatorio es el de cargar imagen, pero permite agregar archivos que no son imágenes (JPG, PNG)

# Evidencia
_Imagen del formulario_
![imagen](https://github.com/user-attachments/assets/36605bff-8f3a-490d-80d3-b6185c2cab59)

_Imagen de como queda en la base de datos_
![imagen](https://github.com/user-attachments/assets/23272cc7-bedd-494b-b78c-8009dcb6c9b9)

# Resultados esperados

1. Se espera que todos los campos en el formulario sean obligatorios y que solo acepte archivos con las siguientes extensiones:
- jpg
- jpeg
- jfif
- pjpeg
- pjp
- png

2. Se espera que cuando se diligencie el formulario aparezca un mensaje 'PopUp' donde informe si se pudo crear la propiedad o no

**Comment by valleedev** [comment]
Ya todos los campos son requeridos, solo admite formatos de imagen y aparece el popup : )
