### ISSUE TITLE
Bug en la sección de Servicios

### ISSUE THREAD

**Issue by Jean-Paul-19** [EmmanuelOcLe/inmobiliaria#13]
Al momento de hacer clic en el botón de "Arrienda ya ", hay incoherencias con las propiedades que deberían mostrarse.
Prueba:

![Captura de pantalla 2024-12-15 184556](https://github.com/user-attachments/assets/07daff82-2eaf-49c8-bec5-2863dcd1726f)

-----------------------------------------------------------------------------------------------------------------------------------------------------

Se deberían mostrar las propiedades que están en arriendo.

Ej:

![Captura de pantalla 2024-12-15 184911](https://github.com/user-attachments/assets/c8187be0-49c4-4f0e-be53-b8a0af779c97)

P.D : El error es igual para el botón de "Compra Ya", ya que tiene incoherencias con las propiedades que deberían mostrarse.

Prueba:

![Captura de pantalla 2024-12-15 185136](https://github.com/user-attachments/assets/83412979-114f-42c8-bb88-6e38d444dcfb)

**Comment by valleedev** [comment]
Se reorganizaron las consultas sql para aplicar bien los filtros
