### ISSUE TITLE
Error venta-arriendo

### ISSUE THREAD

**Issue by michael-myers-myke** [EmmanuelOcLe/inmobiliaria#14]
#error venta arriendo
la etiqueta no logra visualizarse de manera correcta
![Captura de pantalla 2024-12-16 012750](https://github.com/user-attachments/assets/62117404-ff9c-4661-a191-b0a70887d6eb)

**Comment by valleedev** [comment]
# SOLUCIÓN
al enviar los datos desde el formulario de crear la propiedad estaba enviando en el metodo post venta-arriendo, pero el enum de la base de datos recibe es venta - arriendo, entonces se cambio en el formulario
![image](https://github.com/user-attachments/assets/531982a5-4c3c-4efe-9c8a-d5c5678a950a)
