### ISSUE TITLE
El reporte de excel no tiene el campo 'oferta' como el reporte PDF

### ISSUE THREAD

**Issue by EmmanuelOcLe** [EmmanuelOcLe/inmobiliaria#3]
# Resultado esperado
Los reportes siguen una estructura estandar donde aparecen los siguiente campos:
- Id
- Nombre
- Ubicación
- Habitaciones
- Baños
- Parking 
- Área
- Oferta
- Precio
- Estado (habilitado, inhabilitado)

### Se espera que el reporte de excel muestre una columna 'Oferta' que contenga los valores del tipo de oferta del inmueble (venta, alquiler).

# Resultado obtenido
El reporte de excel muestra todos los campos que debe llevar excepto el campo de 'Oferta'. En lugar de obtener el campo de oferta, aparece el campo 'Descripción' que no se incluye en los reportes.

# Evidencia
![imagen](https://github.com/user-attachments/assets/c4954762-c92c-4779-825e-8c461e1343c6)

# Pasos a seguir
1. Reemplazar la columna de 'Descripción' con la columna 'Oferta'
2. Agregar los datos correspondientes

**Comment by valleedev** [comment]
# SOLUCIÓN
Se elimina el campo de descripción y se remplaza por el tipo de oferta
# EVIDENCIA
![image](https://github.com/user-attachments/assets/03ae8fb2-9304-4b82-b7ca-04c83a988036)
