### ISSUE TITLE
Base de datos en servidor o en linea

### ISSUE THREAD

**Issue by EileenLiduenez** [EmmanuelOcLe/inmobiliaria#5]
### Crear base de datos en linea 

Se debe crear una base de datos en un servidor o en linea para llevar todo la misma conexion del proyecto y los inmuebles, ya se segir trabjandolo de forma local genera choques entre paginas 

![image](https://github.com/user-attachments/assets/738eae4e-34c4-46e2-85ab-6d278036b44e)

**Comment by valleedev** [comment]
Esta issue la cerramos porque somos unos tíos chill de cojones y mañana todo va a salir bien
