### ISSUE TITLE
No se carga la imagen del  navbar en el index

### ISSUE THREAD

**Issue by valleedev** [EmmanuelOcLe/inmobiliaria#9]
# Resultado esperado
Se espera que en el navbar se muestre la imagen del mocup
![image](https://github.com/user-attachments/assets/9da33498-5802-4807-b970-1da8f7ef86a9)
# Resultado actual
La imagen no se esta cargando y aparece en negro el background
# Evidencia
![image](https://github.com/user-attachments/assets/1d1aa4fd-01d7-4c85-8532-bec3c45e9c55)

**Comment by juanda1121** [comment]
# solucion en las imagenes del navbar

![Captura de pantalla 2024-12-15 132412](https://github.com/user-attachments/assets/95534f73-e550-41d0-b8d3-3cd289d2b449)
